language: generic

services:
  - docker

before_install:
  - docker build -t bvalerin/react_app -f Dockerfile.dev .

script:
  - docker run -e CI=true bvalerin/react_app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-431623332495"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY